version: '3'
services:
  among-us-jp-bot:
    build:
      context: .
      dockerfile: local/Dockerfile
    stdin_open: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start
